# Generated by Django 4.2 on 2024-07-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phon_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='iscomplated',
            new_name='is_completed',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='adres',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
