# Generated by Django 4.2 on 2024-07-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_phon_number_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='adres',
            new_name='address',
        ),
    ]
