# Generated by Django 4.2 on 2024-07-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustUser',
        ),
    ]
